project:
  name: HelloWorld
  default: build
  basedir: .
  properties:
    src.dir: src
    build.dir: build
    classes.dir: ${build.dir}/classes
    jar.dir: ${build.dir}/jar
    main-class: com.example.HelloWorld
  classpath:
    dir: ${lib.dir}
    includes: "**/*.jar"
  targets:
    clean:
      delete:
        dir: ${build.dir}
    compile:
      depends: clean
      mkdir:
        dir: ${classes.dir}
      javac:
        srcdir: ${src.dir}
        destdir: ${classes.dir}
        includeantruntime: false
        classpathref: classpath
    jar:
      depends: compile
      mkdir:
        dir: ${jar.dir}
      jar:
        destfile: ${jar.dir}/${ant.project.name}.jar
        basedir: ${classes.dir}
        manifest:
          attribute:
            name: Main-Class
            value: ${main-class}
    run:
      depends: jar
      java:
        jar: ${jar.dir}/${ant.project.name}.jar
        fork: true
    build:
      depends: run
